steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: unfollowlens/cloud-run
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/unfollowlens-proxy:$COMMIT_SHA
      - .

images:
  - gcr.io/$PROJECT_ID/unfollowlens-proxy:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
